### ISSUE TITLE
Scale issues with CI

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore-examples#20]
Eventually as we accumulate many example scripts, we will probably run into issue with having CI on this repo, since it will probably take a long time to run all the scripts and exceed the CI timeout.

**Comment by devtty1er** [comment]
To some extent, https://github.com/devtty1er/manticore-examples/commit/95a786a0b68fe8cac42b01e65d31efa0fc3c7914 addresses past Travis CI build failures due to `scripts/travis_test.sh` timeouts after 10 minutes ([example](https://travis-ci.org/trailofbits/manticore-examples/builds/380455765)); however, this doesn't address when the total run time of the Travis Ci build exceeds 50 minutes. One solution I've seen (although arguably poor form) is to put each example in a separate branch and list each example branch and its Travis CI badge in master.

**Comment by ehennenfent** [comment]
We're at about 8 minutes right now, and can break this up as much as we need to.
